services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d # Correct path
      - postgres_data:/var/lib/postgresql/data

  enthalpy_app:
    depends_on:
      - postgresdb
    build: ./
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgresdb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432

volumes:
  postgres_data:
