import Anthropic from "@anthropic-ai/sdk";
import {
  MessageParam,
  ContentBlockParam,
  ContentBlock,
  Tool as AnthropicTool
} from "@anthropic-ai/sdk/resources";
import { ModelMessage, Tool, AssistantModelMessage, ComputerTool, ComputerToolInput } from "@enthalpy/shared";
import {
  modelMessageSchemaUpdated as modelMessageSchema,
  modelMessageZodSchema
} from "../../schemas/modelMessageSchemaUpdated.js";
import { prompts } from "../../schemas/mcprompts.js";
import { computerUseToolInputSchema } from "../../schemas/toolSchemas.js";
import util from 'util';

export interface LLMIntf {
  providerName: string,
  model: string;
  input: (msg: Array<ModelMessage>) => Promise<ModelMessage>
}

export class ClaudeIntf implements LLMIntf {
  providerName: string = "claude";
  // model: string = "claude-haiku-4-5-20251001";
  model: string = "claude-sonnet-4-5-20250929";
  maxTokens: number = 1024;
  client: Anthropic;

  constructor() {
    if (process.env.ANTHROPIC_KEY === undefined) {
      console.log("Set the env variable ANTHROPIC_KEY");
    }
    this.client = new Anthropic({
      apiKey: process.env.ANTHROPIC_KEY,
    });
  }

  static translateToAnthropicMessage(msg: ModelMessage): MessageParam {
    let blocks = Array<ContentBlockParam>();
    msg.contents.forEach(m => {
      blocks.push({
        type: "text",
        text: JSON.stringify(m)
      });
    })
    return {
      role: msg.role,
      content: blocks
    }
  }

  static translateToAnthropicMessages(msgs: Array<ModelMessage>):
    Array<MessageParam> {
    let anthMsgs = Array<MessageParam>();
    msgs.forEach((msg2: ModelMessage) => {
      // console.log("DEBUGGING: model message2: ",  JSON.stringify(msg2));
      anthMsgs.push(ClaudeIntf.translateToAnthropicMessage(msg2));
    });
    return anthMsgs;
  }

  static getToolSchemas(t: Tool): any {
    if(t.name === "computer_use") {
      return computerUseToolInputSchema;
    } else {
      return {};
    }
  }

  static translateToAnthropicTool(tools: Array<Tool>):
    Array<AnthropicTool> {
    let anthTools = Array<AnthropicTool>();
    tools.forEach((tool: Tool) => {
      // console.log("DEBUGGING: model message2: ",  JSON.stringify(msg2));
      anthTools.push({
        type: "custom",
        description: tool.description,
        input_schema: ClaudeIntf.getToolSchemas(tool),
        name: tool.name
      });
    });
    return anthTools;
  }

  async input_test(): Promise<ModelMessage> {
    return {
        role: "assistant",
        contents: [
          {
            type: "output_to_user",
            content: "Some content for the user generated by the agent."
          },
          {
            type: "workflow_context",
            content: "Some context gathered by the LLM"
          }
        ]
      };
  }

  async input(msgs: Array<ModelMessage>,tools?: Map<string,Tool>): Promise<ModelMessage> {
    // return this.input_test();
    console.log("Sending these input messages: ",msgs);
    // const message = await this.client.messages
    const message = await this.client.beta.messages
      .create({
        max_tokens: this.maxTokens,
        betas: ["structured-outputs-2025-11-13"],
        messages: ClaudeIntf.translateToAnthropicMessages(msgs),
        model: this.model,
        system: prompts["system-prompt"],
        tools: ClaudeIntf.translateToAnthropicTool(tools ? Array.from(tools.values()) : []),
        output_format: {
          type: "json_schema",
          schema: modelMessageSchema
        }
      })
      .catch((error) => {
        console.log(error);
      });
    // console.log("Got this message from the claude model", message);
    //TODO: translate the content blocks to ModelMessage format
    if (message === undefined || message === null) {
      return Promise.resolve({
        role: "assistant",
        contents: []
      });
    } else {
      let msg: AssistantModelMessage = {
        role: "assistant",
        contents: []
      };
      let contents = message.content as Array<ContentBlock>;
      contents.forEach((content: ContentBlock) => {
        if(content.type === "text") {
          if (content.text) {
            try {
              let modified = content.text.replace(/^```json|```$/g,"");
              let modifiedp: any = JSON.parse(modified);

              // Validate using Zod
              const validationResult = modelMessageZodSchema.safeParse(modifiedp);

              if(validationResult.success) {
                // console.log("Model output conforms to the schema, got this messages array: ",
                  // modifiedp.messages);
                let modifiedpv: AssistantModelMessage = modifiedp as AssistantModelMessage;
                msg.contents = msg.contents.concat(modifiedpv.contents);
              } else {
                console.log("Model output message does not conform to the schema");
                console.log("Validation errors:", validationResult.error);
                console.log("Received data:", util.inspect(modifiedp, { depth: null, colors: true }));
              }
            } catch(e) {
              console.log(`Parsing model output as JSON probably failed. Got LLM output ${content.text}`);
              console.log("Error when processing LLM response", e);
            }
          }
        } else if(content.type === "tool_use" && tools) {
          const toolId = content.id; 
          const toolName = content.name; 
          const input = content.input; 
          if(tools.has(toolName)) {
            if(toolName === "computer_use") {
              const computerUseInput = input as ComputerToolInput;
              msg.contents = msg.contents.concat([{
                type: "tool_use",
                content: new ComputerTool(toolId,computerUseInput)
              }]);
            }
          }
        }
      });
      return msg;
    }
  }
}
